import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import Navbar from "@/components/component/Navbar";
import { AuthProvider } from "@/context/AuthContext";
import AppLoadingOverlay from "@/components/ui/app-loading-overlay";
import QueryProvider from "@/components/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <QueryProvider>
            <Navbar/>
            <main className="min-h-screen pt-20 md:pt-24">
              {children}
            </main>
            <AppLoadingOverlay/>
          </QueryProvider>
        </AuthProvider>

        <Toaster/>
      </body>
    </html>
  );
}
